// For simplicity, using very small placeholder base64 images.
// In a real application, these would be higher quality thumbnails.

interface Suggestion {
  name: string;
  image: string;
}

export const suggestionData: Suggestion[] = [
  {
    name: 'Đứng cạnh một chiếc siêu xe Ferrari màu đỏ',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcDBAUC/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDBAAFEQYSITEiMkFRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANjxbk8K0x3I7K1F90YUUpJCR6k+tZ1m9Ld6ZcFtxbXFkRVK2peWkpWPqADg/Wp25X1t99bFqjOS3k9yEdJPr48VmuK3X1qJm29MdtR0h4HcR744qFEX//Z',
  },
  {
    name: 'Đứng cạnh siêu xe Lamborghini màu vàng',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcDBAUC/8QAJBAAAQMDAwQDAAAAAAAAAAAAAQIDBAAFERIhBgciMUFRYXH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABURAQEAAAAAAAAAAAAAAAAAAAEh/9oADAMBAAIRAxEAPwDY8S/3C0Q3IsZpSnXRhRCSRj0z61lWfqZc7XcVx7mxHlxioIW8ElCwPUgDBqfuV9bfkLi2mM5LeRwpI6Un148Vm3Bbr6lEzbbTDayNIdB3E++OKgRf//Z',
  },
  {
    name: 'Đứng cạnh siêu xe Bugatti màu xanh',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAcIBQP/xAAlEAABAwMDAwUAAAAAAAAAAAABAgMEAAUREgYhBxMxUSJBcbH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAEA/9oADAMBAAIRAxEAPwDZsS5XC2w3IsZlSnHThZCSQPYH3rKM9U7va7iqPcYkeXFUsJW8AlCwPUkDBqcuV+aefVFs8Z2W+ngpHSlXrx4rOOK3XnSol25pllZwpDwO4j3xxRF//Z',
  },
  {
    name: 'Tay dắt một chú chó Husky',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGgAAAgMBAQAAAAAAAAAAAAAAAAgDBQcEAf/EACUQAAEDAwMDBQAAAAAAAAAAAAECAwQABREGBxIhCBMxUSJCYf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDXuK+XK2RXIsVhxTrwwskEggcgD3rJsf1LvdquKo9ziRZkRSwl18BCFgdwSMGpy635h99UOzxnZb6eCkdKVevHjNYxxa7K0qJuWmmWlHCHQd2Pc44pIv/9k=',
  },
  {
    name: 'Đứng trên bãi cát ngắm hoàng hôn',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGwAAAgMBAQEAAAAAAAAAAAAABgcDBQIEAf/EACYQAAEDAwMDBQEAAAAAAAAAAAECAwQABREGBxIhCBMxMkFRYXH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAEA/9oADAMBAAIRAxEAPwDbuK+XK2RHI0VpxTzw2kkEgDkAD3rIsf1LvdquC49ziRZkRSgl18BCFgdwSMGpy635p95UW0xnZb6OCkHoSr148GsW4rdeWlRNy10yyrOFocB3Y9zjikRf/2Q==',
  },
  {
    name: 'Ngồi trong quán cafe ở Paris',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGwAAAgMBAQEAAAAAAAAAAAAABgcEBQgDAv/EACUQAAEDAwMDBQAAAAAAAAAAAAECAwQABREGEgcxIRMyUSJCYf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDduK+XK2RXI0Vhxx54bSSCQByAAe9ZFi+pd7tVwXHc4kWZEUoJdfAQsA9wSMGpy631p95UOzRnZb6OCkdKVevHjNYtxt11aVEzLvTDKzhSHAd2Pc44pIv/2Q==',
  },
  {
    name: 'Đi bộ trên đường phố Tokyo về đêm',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGwAAAgMBAQEAAAAAAAAAAAAABAYHCAMFAn/xAAlEAABAwMDAwUAAAAAAAAAAAABAgMEAAUREgYhBxMxQRQiUWH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAEA/9oADAMBAAIRAxEAPwDbOK9XG1RXIkZpSnXRhZCSQB6A+9ZVm6nXO13FUe5xI8uKpaQt4BKFgdwSMGpy531l95cWzxXZbyOFJHSk+vHisq4rdfeWkTdvabZWQpLwO4j3xxRF//Z',
  },
   {
    name: 'Đứng trên sân thượng tòa nhà lớn',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGwAAAgMBAQEAAAAAAAAAAAAABgcEBQgDAv/EACcQAAEDAwMDBQEAAAAAAAAAAAECAwQABREGEgcxIRNBIiMyUWGR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDduK+XK2RXIsVhxTrwwskEggcgD3rJsf1LvdquKo9ziRZkRSwl18BCFgdwSMGpy635h99UOzxnZb6eCkdKVevHjNYxxa7K0qJuWmmWlHCHQd2Pc44pIv/2Q==',
  },
  {
    name: 'Đứng cạnh Lionel Messi',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcDBAUC/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDBAAFEQYSITEiMkFRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANjxbk8K0x3I7K1F90YUUpJCR6k+tZ1m9Ld6ZcFtxbXFkRVK2peWkpWPqADg/Wp25X1t99bFqjOS3k9yEdJPr48VmuK3X1qJm29MdtR0h4HcR744qFEX//Z',
  },
  {
    name: 'Đứng cạnh Cristiano Ronaldo',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcDBAUC/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDBAAFEQYSITEiMkFRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANjxbk8K0x3I7K1F90YUUpJCR6k+tZ1m9Ld6ZcFtxbXFkRVK2peWkpWPqADg/Wp25X1t99bFqjOS3k9yEdJPr48VmuK3X1qJm29MdtR0h4HcR744qFEX//Z',
  },
  {
    name: 'Đứng cạnh Neymar Jr.',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcDBAUC/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDBAAFEQYSITEiMkFRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANjxbk8K0x3I7K1F90YUUpJCR6k+tZ1m9Ld6ZcFtxbXFkRVK2peWkpWPqADg/Wp25X1t99bFqjOS3k9yEdJPr48VmuK3X1qJm29MdtR0h4HcR744qFEX//Z',
  },
  {
    name: 'Đứng cạnh Ronaldinho',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcDBAUC/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDBAAFEQYSITEiMkFRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANjxbk8K0x3I7K1F90YUUpJCR6k+tZ1m9Ld6ZcFtxbXFkRVK2peWkpWPqADg/Wp25X1t99bFqjOS3k9yEdJPr48VmuK3X1qJm29MdtR0h4HcR744qFEX//Z',
  },
  {
    name: 'Đứng cạnh Taylor Swift',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcDBAUC/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDBAAFEQYSITEiMkFRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANjxbk8K0x3I7K1F90YUUpJCR6k+tZ1m9Ld6ZcFtxbXFkRVK2peWkpWPqADg/Wp25X1t99bFqjOS3k9yEdJPr48VmuK3X1qJm29MdtR0h4HcR744qFEX//Z',
  },
  {
    name: 'Đứng cạnh Sơn Tùng M-TP',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcDBAUC/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDBAAFEQYSITEiMkFRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANjxbk8K0x3I7K1F90YUUpJCR6k+tZ1m9Ld6ZcFtxbXFkRVK2peWkpWPqADg/Wp25X1t99bFqjOS3k9yEdJPr48VmuK3X1qJm29MdtR0h4HcR744qFEX//Z',
  },
  {
    name: 'Đứng cạnh Triệu Lệ Dĩnh',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcDBAUC/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDBAAFEQYSITEiMkFRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANjxbk8K0x3I7K1F90YUUpJCR6k+tZ1m9Ld6ZcFtxbXFkRVK2peWkpWPqADg/Wp25X1t99bFqjOS3k9yEdJPr48VmuK3X1qJm29MdtR0h4HcR744qFEX//Z',
  },
  {
    name: 'Đứng cạnh Dương Mịch',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcDBAUC/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDBAAFEQYSITEiMkFRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANjxbk8K0x3I7K1F90YUUpJCR6k+tZ1m9Ld6ZcFtxbXFkRVK2peWkpWPqADg/Wp25X1t99bFqjOS3k9yEdJPr48VmuK3X1qJm29MdtR0h4HcR744qFEX//Z',
  },
  {
    name: 'Đứng cạnh Thành Long (Jackie Chan)',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcDBAUC/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDBAAFEQYSITEiMkFRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANjxbk8K0x3I7K1F90YUUpJCR6k+tZ1m9Ld6ZcFtxbXFkRVK2peWkpWPqADg/Wp25X1t99bFqjOS3k9yEdJPr48VmuK3X1qJm29MdtR0h4HcR744qFEX//Z',
  },
  {
    name: 'Đứng cạnh Elon Musk',
    image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAoACgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcDBAUC/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDBAAFEQYSITEiMkFRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANjxbk8K0x3I7K1F90YUUpJCR6k+tZ1m9Ld6ZcFtxbXFkRVK2peWkpWPqADg/Wp25X1t99bFqjOS3k9yEdJPr48VmuK3X1qJm29MdtR0h4HcR744qFEX//Z',
  },
  {
    name: 'ngồi trong chiếc xe mui trần',
    image: '',
  },
  {
    name: 'Tạo dáng đứng thẳng',
    image: '',
  },
  {
    name: 'Tạo dáng ngồi trên ghế',
    image: '',
  },
  {
    name: 'Tạo dáng ôm một chú chó',
    image: '',
  },
  {
    name: 'Tạo dáng đi bộ trên phố',
    image: '',
  },
  {
    name: 'Tạo dáng dựa vào tường',
    image: '',
  },
  {
    name: 'Tạo dáng nhảy lên không trung',
    image: '',
  },
  {
    name: 'Tạo dáng nhìn xa xăm',
    image: '',
  },
  {
    name: 'Tạo dáng cool ngầu',
    image: '',
  },
  {
    name: 'Tạo dáng cười rạng rỡ',
    image: '',
  },
  {
    name: 'Tạo dáng high fashion',
    image: '',
  }
];